FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:6.2.2
