version: '2.2'
services:
    elasticsearch:
        build: .
        image: es:pl
        container_name: es
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnet
    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.2.2
        depends_on: 
            - elasticsearch
        container_name: kib
        networks:
            - esnet


volumes:
    esdata:
        driver: local

networks:
    esnet: 
